### ISSUE TITLE
Work without having to use protocol

### ISSUE THREAD

**Issue by midudev** [d4nidev/carl#4]
As curl replacement I expect to execute it as `carl midudev.com` and get a valid response without having to put the protocol of the url. In `curl` is not needed and could be a good addition in order to simplify the use.

Instead, I get:
```
Error: only absolute urls are supported
    at /Users/miguelangel.duran/.npm/_npx/22688/lib/node_modules/carl-cli/node_modules/node-fetch/index.js:54:10
    at new Promise (<anonymous>)
    at new Fetch (/Users/miguelangel.duran/.npm/_npx/22688/lib/node_modules/carl-cli/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/miguelangel.duran/.npm/_npx/22688/lib/node_modules/carl-cli/node_modules/node-fetch/index.js:37:10)
    at module.exports (/Users/miguelangel.duran/.npm/_npx/22688/lib/node_modules/carl-cli/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at doFetch (/Users/miguelangel.duran/.npm/_npx/22688/lib/node_modules/carl-cli/cli.js:11:3)
    at Object.<anonymous> (/Users/miguelangel.duran/.npm/_npx/22688/lib/node_modules/carl-cli/cli.js:31:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

**Comment by delacruz-dev** [comment]
Solved in https://github.com/d4nidev/carl/releases/tag/1.2.0
